### ISSUE TITLE
Choose where to output footnotes?

### ISSUE THREAD

**Issue by joejoinerr** [distantnative/footnotes#14]
Really great plugin. Great improvement over MultiMarkdown.

However, I'm building a blog where I need to separate the footnotes from the article text to another section after some other content. Is it possible to choose where to output the footnote list?

If not, could I request this as a feature? It'd be awesome if you could get it to work.

Thanks!

**Comment by distantnative** [comment]
I like the idea, but can't promise yet when I will find time to include it. But it's on my list :)

**Comment by joejoinerr** [comment]
That's great, thanks!

**Comment by distantnative** [comment]
Got a first version on the develop branch. Works by first disabling the bibliography on your field:

```php
<?php echo $page->text()->footnotes(array('bibliography' => false))->kirbytext() ?>
```

and then getting the bibliography wherever you want it by calling:

```php
    <?php echo Footnotes::bibliography($page->text()) ?>
```

Let me know if it works for you!

**Comment by joejoinerr** [comment]
Apologies for taking so long to get back to you. This is great! The footnotes are showing up where I want them now, so that's perfect.

However, I noticed on articles which don't have footnotes, the `.footnotes` wrapper and empty nested `ol` are still injected into the page. Is there any way to avoid this?

**Comment by joejoinerr** [comment]
Is there any way to stop the bibliography outputting an `<ol>` tag if there are no footnotes in the text?

**Comment by distantnative** [comment]
Just fixed it in a commit on the develop branch.
