### ISSUE TITLE
Snippet entry.php $number undefined

### ISSUE THREAD

**Issue by krisak** [distantnative/footnotes#16]
In snippet entry.php there is variable $number at line 5

`<li id="fn-<?= $count ?>" value="<?= $number ?>"><?= $note ?> <span class="footnotereverse"><a href="#fnref-<?= $count ?>">&#8617;</a></span></li>`

It throws errors and strangely i could not find the $number in any of lib files so idk what is it referencing. Isnt the value there just the show the number of footnote so it should be again $count?

**Comment by distantnative** [comment]
Could you test if it resolves your error if you replace `$number` with `$order` in the `snippets/entry.php`?

**Comment by andredjdn** [comment]
I had the same issue. Replacing `$number` with `$order` in `snippets/entry.php` sovled the problem for me.
