### ISSUE TITLE
Uncaught SyntaxError: Unexpected token &

### ISSUE THREAD

**Issue by afincato** [distantnative/footnotes#18]
Hello!
Great plugin (nice the option to output a footnote outside of the `div` to which the main text belong to).

I am having this problem when using it, though:

`Uncaught SyntaxError: Unexpected token &` 

which points to the inline script in the very first footnote of a text:

`<p>Through these close readings, I aim to reveal alternative cultural narratives for becoming both immaterially and materially determined user-agents in order to avoid a re-territorialization by human-as-centrifugal force in designing the future.<script>document.addEventListener(&quot;DOMContentLoaded&quot;,function(){&quot;use strict&quot;;for(var e=document.querySelectorAll('.footnote &gt; a[href<em>=&quot;#&quot;]:not([href=&quot;#&quot;]), .footnotereverse &gt; a[href</em>=&quot;#&quot;]:not([href=&quot;#&quot;])'),t=e.length,n=/firefox|trident/i.test(navigator.userAgent)?document.documentElement:document.body,o=function(e,t,n,o){return(e/=o/2)&lt;1?n/2<em>e</em>e<em>e+t:n/2</em>((e-=2)<em>e</em>e+2)+t};t--;)e.item(t).addEventListener(&quot;click&quot;,function(e){var t,r=n.scrollTop,i=document.getElementById(/[^#]+$/.exec(this.href)[0]).getBoundingClientRect().top+200,c=n.scrollHeight-window.innerHeight,u=c&gt;r+i?i:c-r,d=500,a=function(e){t=t||e;var i=e-t,c=o(i,r,u,d);return n.scrollTop=c,d&gt;i&amp;&amp;requestAnimationFrame(a)};requestAnimationFrame(a),e.preventDefault()})});</script></p>  </div>
`

I wonder if it is because of the `&quot;`?

Tell me if you need more informations!

**Comment by afincato** [comment]
In my use case I need to output the footnotes on a `div` different from the one of the main text. So I have to split `$page->text()` from `$page-text()->footnotes()`.

I just discovered that if I don't use this
```
$page->text()->footnotes(['bibliography' => false])
```

to prevent the plugin from printing the footnotes in the main body-text `div`, and I still use this function to print the footnotes on a different `div` 
```
echo dnFootnotes::bibliography($page->text())
```

the above problem disappears.

It also doesn't happen if I simply print the footnotes like this

```
$page->text()->footnotes()
```

so it only manifests when there is a need to output footnotes away from the main text-field.

Hope this helps you to track the problem down, the plugin is great.

**Comment by distantnative** [comment]
Could it be that you are also using the `->html()` method on the field? Like `$page->text()->footnotes(['bibliography' => false])->html() `?

**Comment by afincato** [comment]
No, but I was using the `->kirbytext()` method

```
<?php echo $page->text()->footnotes(['bibliography' => false])->kirbytext() ?>
```

Could have been this the problem?

**Comment by distantnative** [comment]
I could reproduce the error with using the `html()` method, not the `kirbytext()` method. However, I think you should be able to fix it by using first kirbytext, then footnotes:

```
<?php echo $page->text()->kirbytext ()->footnotes(['bibliography' => false]) ?>
```

**Comment by afincato** [comment]
Cool that works.

My template now requires to use the `kirbytext` helper, so it looks like this:

```
<?php echo kirbytext($page->text() . '<span class="blog-article__body-text--ending-mark">🝏</span>') ?>
```

and with this new syntax you suggested, it does not work

```
<?php echo kirbytext($page->text() . '<span class="blog-article__body-text--ending-mark">🝏</span>') ()->footnotes(['bibliography' => false]) ?>
```

It says
```
syntax error, unexpected '(', expecting ',' or ';'
```

Any idea? Thank you for looking into this!

**Comment by distantnative** [comment]
Ok, this won't look nice but could work:

```
<?php echo Kirby\distantnative\Footnotes\Methods::field(kirbytext($page->text() . '<span class="blog-article__body-text--ending-mark">🝏</span>'), ['bibliography' => false]) ?>
```

But wondering if you could not also use

```
<?php echo $page->text()->kirbytext ()->footnotes(['bibliography' => false]) . '<span class="blog-article__body-text--ending-mark">🝏</span>' ?>
```

**Comment by afincato** [comment]
Firs snippet throws an error back 
```
Trying to get property of non-object
```

Second snippet works, but the special character I want to add at the end of the text should be within `kirbytext`, while using the second method you shared print the character outside of `kirbytext`.

That's why I was using `kirbytext` helper in this case. Not sure how to proceed and strangely if I don't add `->footnotes(['bibliography' => false])` after `$page->text()->kirbytext()`, the footnotes work anyway.

Do you think there might be another way to do this?

**Comment by distantnative** [comment]
Honestly, I have no idea where this `<br>` in your setup comes from, can't reproduce it.
