### ISSUE TITLE
Space before footnote in text

### ISSUE THREAD

**Issue by S1SYPHOS** [distantnative/footnotes#22]
Hey there,
I didn't especially like the extra space right before the footnote, which comes from the php if statement in reference.php, and since normally when working with footnotes (eg scientific papers) you don't expect extra spaces to show up, I'd vote for removing it - even if it makes the code a bit uglier :v:

**Comment by S1SYPHOS** [comment]
And on a side note: How when using `<?= KirbyFootnotes::bibliography($page->text()) ?>` can I only add footnotes if the text has any?

Mucho appreciado!

**Comment by distantnative** [comment]
I'm currently traveling in Mexico doing research for my PhD. I will be back on a laptop by the end of the month and then I'll look at this in detail.

**Comment by distantnative** [comment]
The issue with the extra space should be fixed on the develop branch now. Could you check and see if it works for you as well?

**Comment by ningwie** [comment]
Using the code from the develop branch the extra space is gone :)
