### ISSUE TITLE
Idea: Merge same Footnotes

### ISSUE THREAD

**Issue by servicethinker** [distantnative/footnotes#6]
![bildschirmfoto 2015-06-13 um 00 23 28](https://cloud.githubusercontent.com/assets/980778/8141078/78c54d24-1162-11e5-9256-01fb4a58a745.png)

Sometimes I have two times the same reference or footnote in one article. I would love to set a merging option in my config like 
`c::set('footnotes.merge', true);`
to automatically merge equally footnotes together to have just one reference with the same footnote digit.

**Comment by distantnative** [comment]
Uhh, I like the idea, will see what I can do :)

**Comment by distantnative** [comment]
Added a first approach to the `develop` branch. It seems to work in my first tests, but I'm always happy to hear from the performance in broader test scenarios :)

**Comment by servicethinker** [comment]
Sadly this doesn't work for me; getting this:

```
Warning: preg_replace(): Unknown modifier '>' in [...]/footnotes.php on line 83
```

**Comment by distantnative** [comment]
Can you provide the footnotes (I'd assume one has a `>` as footnote text)? Will need to work a lil more on character escaping

**Comment by servicethinker** [comment]
Here they are:

```
(citeauthor: Jonathan Ive [1. Jonathan Ive: Interview bei <a href="https://youtu.be/ef69BUlge-A" target="_blank">Vanity Fair's Graydon Carter</a>, 2014])
(citeauthor: Steve Krug [1. Steve Krug: *Don't Make Me Think, Revisited: A Common Sense Approach to Web and Mobile Usability*], frei übersetzt)
[5. Matthias Jöst: *Adapting to the User*, In: *Ubiquitous and Pervasive Computing: Con- cepts, Methodologies, Tools, and Applications* (2010), S. 1006–1020]
[4. <a href="http://devstreaming.apple.com/videos/wwdc/2014/708xxvfd08bdof2/708/708_taking_core_location_indoors.pdf" title="Apple - WWDC - Taking Core Location Indoors" target="_blank">Apple Inc.: *Taking Core Location Indoors*</a>, WWDC (2014)]
[3. Jan D. S. Wischweh: *Aktivitätsorienterte Kontextadaption für mobile Anwendungen*, Diplomarbeit, Uni Hamburg (2009)]
```

(I think those are good examples how I'm using them actually... - of course I have some more!)

You can find the citeauthor Kirbytag here: https://github.com/servicethinker/Servicethinker.de/blob/master/site/tags/citeauthor.php

Hope this helps...

**Comment by distantnative** [comment]
Just pushed another commit and locally it seems to work with your example footnotes (which are quite good for testing, I guess, given the links, kirbytext markups etc.) - does it work for you as well?

**Comment by servicethinker** [comment]
Now it works. Thank you! :D
