### ISSUE TITLE
Idea: Ignore footnotes on defined templates.

### ISSUE THREAD

**Issue by servicethinker** [distantnative/footnotes#7]
I love to have the footnote functionality globally. So I don't have to specify which templates I want to enable.

But sometimes there are just one or just two templates which shouldn't have any footnotes. For example: an RSS feed would be very ugly with footnotes Javascript on the bottom of every article. But most of the time it's the only template that shouldn't have some.

I think something like this in the config file would be very cool: 
```
c::set('footnotes.ignore', array(
  'feed'
));
```

Possible?

**Comment by distantnative** [comment]
On the develop branch there is already somewhat of a solution:

```php
c::set('footnotes.templates', array(
  'about',
  'blog',
  'project-.*'
));
```

It's the other way around: global footnotes will restricted to the templates specified. Atm basic regular expressions are possible. Not sure if this will stay. Also not sure if I shouldn't put it the other way as you asked for (ignore list).

**Comment by distantnative** [comment]
Actually not only on the develop branch, but also in the last release.

**Comment by servicethinker** [comment]
In my opinion both ways - restricted and ignored - are important. restricted is good to use the footnotes only on a few templates. On the other site ignoring few templates while using footnotes on almost every other site is also a good point for robust architecture design.

**Comment by distantnative** [comment]
Has been added to the development branch:

>**Template whitelist**  
>You can allow footnotes only on specific templates by adding the following to your `site/config/config.php`:
>```php
c::set('footnotes.templates.allow', array(
  'about',
  'blog',
  'project'
));
```
>
>**Template blacklist**
>You can restrict footnotes from specific templates by adding the following to your `site/config/config.php`:
>```php
c::set('footnotes.templates.ignore', array(
  'about',
  'blog',
  'project'
));
```

**Comment by servicethinker** [comment]
Works like a charm for me! Thanks!
